on:
  push:
    branchs: main  
  schedule:
    # every UTC 17:00 -> CST (China) 1:00
    - cron: '0 17 * * *'
name: Mirror Github repos to Gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror Github repos to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/Yang-Xijie
        dst: gitee/yang-xijie
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "C-Makefile-template"
        force_update: true
